# Generated by Django 3.0 on 2022-12-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='?', max_length=30)),
                ('username', models.CharField(max_length=300)),
                ('gmail', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('viewed', models.BooleanField(default=False)),
            ],
        ),
    ]
